version: "3.8"

services:
  cart:
    container_name: cart
    image: cart
    build:
      context: ./cart
      dockerfile: ./build/Dockerfile
    ports:
      - "8082:8082" # HTTP
  loms:
    container_name: loms
    image: loms
    build:
      context: ./loms
      dockerfile: ./build/Dockerfile
    ports:
      - "8081:8081" # GRPC
      - "8080:8080" # HTTP
  postgres:
    image: postgres:latest
    restart: always
    deploy:
      replicas: 5
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
