version: "3.8"

services:
  cart:
    container_name: cart
    build:
      context: ./cart
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082" # HTTP
    depends_on:
      loms:
        condition: service_started

  loms:
    container_name: loms
    build:
      context: ./loms
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081" # GRPC
      - "8080:8080" # HTTP
    depends_on:
      postgres:
        condition: service_healthy
      goose:
        condition: service_completed_successfully

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 10

  goose:
    container_name: goose
    image: golang:1.22
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://postgres:postgres@postgres:5432/postgres
    volumes:
      - ./loms/migrations:/migrations
    command: "sh -c 'go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir /migrations up'"

  prometheus:
    container_name: prometheus
    image: bitnami/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - ./grafana/dashboard:/etc/grafana/dashboard/
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

  jaeger:
    container_name: jaeger
    image: bitnami/jaeger:latest
    ports:
      - "16686:16686"
      - "4318:4318"

volumes:
  prometheus_data: {}
  grafana_data: {}
