application_name: "cart"
env: "local"
http:
  host: "cart"
  port: 8082
product:
  base_url: "http://route256.pavl.uk:8080"
  token: "testtoken"
  rps_limit: 10
grpc:
  host: "loms"
  port: 8081
  timeout: 1s
timeout_stop: 10s
tracer:
  host: "http://jaeger"
  port: 4318
