{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MEM alloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"cart:8082\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"loms:8080\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"cart:8082\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "process_cpu_seconds_total{instance=\"loms:8080\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cart", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Cart request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(url) (cart_request_duration_seconds_count)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Cart quantile request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum by(le) (cart_request_duration_seconds_bucket)",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  {
   "title": "Count status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(status_code) (cart_request_duration_seconds_count)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Loms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Loms count request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "loms_request_count{instance=\"loms:8080\", method!~\"/metrics|GET\"}",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}