// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :exec
INSERT INTO outbox (order_id, event_type, status)
VALUES ($1, $2, 'pending')
`

type CreateEventParams struct {
	OrderID   int32
	EventType string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent, arg.OrderID, arg.EventType)
	return err
}

const fetchNextMsgs = `-- name: FetchNextMsgs :many
SELECT order_id, event_type
FROM outbox
WHERE status = 'pending'
ORDER BY created_at
`

type FetchNextMsgsRow struct {
	OrderID   int32
	EventType string
}

func (q *Queries) FetchNextMsgs(ctx context.Context) ([]FetchNextMsgsRow, error) {
	rows, err := q.db.Query(ctx, fetchNextMsgs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchNextMsgsRow
	for rows.Next() {
		var i FetchNextMsgsRow
		if err := rows.Scan(&i.OrderID, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStatus = `-- name: UpdateStatus :exec
UPDATE outbox
SET status = $1,
    updated_at = NOW()
WHERE order_id = $2
  AND event_type = $3
`

type UpdateStatusParams struct {
	Status    pgtype.Text
	OrderID   int32
	EventType string
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) error {
	_, err := q.db.Exec(ctx, updateStatus, arg.Status, arg.OrderID, arg.EventType)
	return err
}
