application_name: "loms"
env: "local"
grpc:
  host: "loms"
  port: 8081
http:
  host: "loms"
  port: 8080
database:
  dsn: "postgres://postgres:postgres@postgres:5432/postgres"
timeout_stop: 10s
tracer:
  host: "jaeger"
  port: 4317
kafka:
  addresses:
    - "kafka:29092"
  topic: "loms.order-events"
  producer_message_interval: 100ms
outbox:
  clear_table_interval: 1h
  old_data_duration: 48h
