// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

type Order struct {
	ID     int32
	UserID int32
	Status string
}

type OrderItem struct {
	OrderID int32
	ItemID  int32
	Count   int32
	Status  string
}

type StocksItem struct {
	Sku        int32
	TotalCount int32
}
